---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "ikigai"
  namespace: "ikigai"
  labels:
    app: "ikigai"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ikigai"
  template:
    metadata:
      labels:
        app: "ikigai"
    spec:
      containers:
      - name: "ikigai"
        image: "rodrigodiez/ikigai:0.1.7"
        env:
          - name: IKIGAI_FITBIT_OAUTH2_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: ikigai-config
                key: oauth2-client-id
          - name: IKIGAI_FITBIT_OAUTH2_REDIRECT_URL
            valueFrom:
              configMapKeyRef:
                name: ikigai-config
                key: oauth2-redirect-url
          - name: IKIGAI_PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
              configMapKeyRef:
                name: ikigai-config
                key: prometheus-pushgateway-host
          - name: IKIGAI_PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
              configMapKeyRef:
                name: ikigai-config
                key: prometheus-pushgateway-port
          - name: IKIGAI_INTERVAL_DURATION
            valueFrom:
              configMapKeyRef:
                name: ikigai-config
                key: interval-duration
          - name: IKIGAI_FITBIT_OAUTH2_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ikigai-secrets
                key: oauth2-client-secret
          - name: IKIGAI_FITBIT_OAUTH2_AUTHORIZATION_CODE
            valueFrom:
              secretKeyRef:
                name: ikigai-secrets
                key: oauth2-authorization-code
---
apiVersion: v1
data:
  oauth2-client-id: 22CT7B
  interval-duration: 60s
  oauth2-redirect-url: http://rodrigodiez.io
  prometheus-pushgateway-host: prometheus-pushgateway-service
  prometheus-pushgateway-port: "9091"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ikigai-config
  namespace: ikigai