version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.local.config.yml:/etc/prometheus/prometheus.yml
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"